name: Dump Entities from Baserow

on:
  schedule:
  - cron: "12 6 * * *"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}
      BASEROW_USER: ${{ secrets.BASEROW_USER }}
      BASEROW_PW: ${{ secrets.BASEROW_PW }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: enrich the data
        run: python enrich_data.py
      - name: dump the data
        run: python dump_data.py
      - name: join the data
        run: python join_tables.py
      - name: convert index files to TEI/XML
        run: python make_xml.py
      - name: make MSDESC TEI/XML
        run: python make_msdesc.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data update from Baserow
